### ISSUE TITLE
Don't see the "Done" button

### ISSUE THREAD

**Issue by Spokane-Dude** [0xced/XCDFormInputAccessoryView#4]
I'm running an iPad app... how do I get the "Done" button to appear?  Other than that, a fantastic piece of code!

**Comment by 0xced** [comment]
It is hidden by default on the iPad to match the behavior of web views but you can get it to appear by setting the `hasDoneButton` property to `YES`.

``` objective-c
XCDFormInputAccessoryView *inputAccessoryView = [XCDFormInputAccessoryView new];
inputAccessoryView.hasDoneButton = YES;
```

**Comment by Spokane-Dude** [comment]
Thank you so much… I appreciate it…

Regards,
Rolf
